### ISSUE TITLE
Paragraph links fails sometimes.

### ISSUE THREAD

**Issue by LiquidZulu** [LiquidZulu/liquidzulu.github.io#136]
The second paragraph in [the-nature-of-law](https://liquidzulu.github.io/the-nature-of-law/#CkS0scO6) failed to be wrapped and the link svg was not inserted next to it.

![image](https://github.com/LiquidZulu/liquidzulu.github.io/assets/34405159/f4036e93-5464-4910-a16d-0eb57fe28979)

**Comment by Bigtruck2** [comment]
In the paragraph link script https://github.com/LiquidZulu/liquidzulu.github.io/blob/source/src/scripts/paragraphLinks.ts there is a check that the paragraph is long enough because it would also wrap footers. The check right now is element.innerText.length>300, but maybe there is some way to exclude paragraphs starting with `<sup><a id="fn.1" href="#fnr.{num}">{num}</a></sup>`.

**Comment by LiquidZulu** [comment]
surely just `element.innerText.startsWith('<sup>')`? Or does it in some way pull out the children elements? I think there was some way to view the raw HTML.

**Comment by Bigtruck2** [comment]
I think it would need to be element.innerHTML but that looks like it would work.

**Comment by Bigtruck2** [comment]
This seems to work. https://github.com/LiquidZulu/liquidzulu.github.io/compare/source...Bigtruck2:liquidzulu.github.io:master
